baseURL = 'https://boricuadndgm.github.io/'
languageCode = 'en-us'
title = 'Boricua D&D GM'
theme = 'hugo-theme-stack'
copyright = "boricuadndgm"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
DefaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

[languages.en]
languageName = "English"
languagedirection = "ltr"
weight = 1

[pagination]
pagerSize = 5

# Permalinks format of each content section
[permalinks]
post = "/p/:slug/"
page = "/:slug/"

### Custom menu
### See https://stack.jimmycai.com/config/menu
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
[menu]
# Configure social menu
[[menu.social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/boricuadndgm"

[menu.social.params]
icon = "brand-github"

[[menu.social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com"

[menu.social.params]
icon = "brand-twitter"

[params]
# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["posts"]
# Output page's full content in RSS.
rssFullContent = false
favicon = "/stargate.ico"

[params.footer]
since = 2025
customText = "All rights reserved and attributions required."

[params.dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[params.sidebar]
emoji = "📜"
subtitle = "Let the dice roll and the adventures unfold!"

[params.sidebar.avatar]
enabled = true
local = true
src = "stargate.png"

[params.article]
headingAnchor = false
math = false
toc = true
readingTime = true

# Related contents configuration
[related]
includeNewer = true
threshold = 60
toLower = false

[[indices]]
name = "tags"
weight = 100

[[indices]]
name = "categories"
weight = 200
