name: Deploy to Github Pages

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    schedule:
      # Update theme automatically everyday at 00:00 UTC
      - cron: "0 0 * * *"
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# Give the default GITHUB_TOKEN write permission to commit and push the
# added or changed files to the repository.
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Pages
              id: pages
              uses: actions/configure-pages@v5

            - name: Cache Hugo resources
              uses: actions/cache@v4
              with:
                  path: resources
                  key: cache-hugo-resources

            - uses: actions/setup-go@v5
              with:
                  go-version: "^1.17.0"
            - run: go version

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: "latest"
                  extended: true

            - name: Build 🔧
              run: hugo --minify --gc --baseURL "${{ steps.pages.outputs.base_url }}/"

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: gh-pages
                  folder: public
                  clean: true
                  single-commit: true
